language: python
python:
  - "3.8"

branches:
  only:
  - /.*/

services:
  - docker

before_install:
  - export VERSION=$(wget -q -O - https://api.github.com/repos/hadolint/hadolint/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget -q https://github.com/hadolint/hadolint/releases/download/v${VERSION}/hadolint-Linux-x86_64 && chmod +x hadolint-Linux-x86_64
  - export VERSION=$(wget -q -O - https://api.github.com/repos/goodwithtech/dockle/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget -q https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz && tar zxf dockle_${VERSION}_Linux-64bit.tar.gz

jobs:
  include:
    - stage: Pytest
      name: Black
      script:
        - pip install black
        - python -m black .

    - stage: Pytest
      name: Isort
      script:
        - pip install isort
        - isort .

    - stage: Pytest
      name: Flake8
      script:
        - ls -lat ../
        - pip install flake8
        - flake8 --config .flake8 .
        